[project]
authors = [
    "oasci <us@oasci.org>",
]
channels = ["conda-forge"]
name = "simlify"
description = "Simplify your molecular simulation workflow."
platforms = ["linux-64", "osx-64"]
version = "0.0.0"
license = "Apache-2.0"
readme = "README.md"

[pypi-dependencies]
simlify = { path = ".", editable = true }
atomea = { git = "https://github.com/oasci/atomea", rev = "285e43ffd1b2742ce6eef99ca917be115f4cfac9" }
pyyaml = ">=6.0.2, <7"

[system-requirements]
linux = "3.10.0"
libc = { family="glibc", version="2.17" }

[environments]
dev = ["dev"]
docs = ["docs"]

[tasks]

[dependencies]
python = "=3.12"
numpy = ">=2.2.4,<3"
scipy = ">=1.15.2,<2"
pydantic = ">=2.10.6,<3"
mdanalysis = ">=2.9.0,<3"

[feature.dev.dependencies]
isort = ">=5.12.0"
pylint = ">=3.0.1"
mypy = ">=1.6.0"
pytest = ">=7.4.2"
pytest-cov = ">=4.1.0"
coverage = ">=7.3.1"
pytest-html = ">=4.0.1"
colorama = ">=0.4.6"
ambertools = ">=24.8,<25"

[feature.dev.tasks]
mdlint = { cmd = ["markdownlint-cli2", '"docs/*.{md,markdown}"', "--fix", "--config", ".markdownlint.yaml", "||", "true"] }
isort = { cmd = ["isort", "--settings-path", ".isort.cfg", "./simlify", "./tests", "||", "true"] }
black = { cmd = ["black", "--config", ".black.toml", "./simlify", "./tests", "||", "true"] }
format = { depends-on = ["mdlint", "isort", "black"] }
tests = { cmd = [
    "PYTHONPATH=.",
    "pytest",
    "-c",
    ".pytest.ini",
    "--cov='simlify'",
    "--cov-report=xml",
    "--junit-xml=report.xml",
    "--failed-first",
]}
coverage = { cmd = ["coverage", "report"] }
cleanup-build = { cmd = ["rm", "-rf", "./build"] }
build = { cmd = ["python3", "-m", "build"], depends-on = ["cleanup-build"]}
publish-test = { cmd = ["twine", "upload", "--repository", "testpypi", "dist/*"] }
publish = { cmd = ["twine", "upload", "dist/*"] }

[feature.dev.pypi-dependencies]
build = ">=1.2.2.post1,<2"
mypy-extensions = ">=1.0.0"
black = { version = ">=23.10.0", extras = ["jupyter"] }
types-pyyaml = ">=6.0.12.20241230, <7"

[feature.docs.dependencies]
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.6.5,<10"
mkdocstrings = ">=0.28.2,<0.29"
mkdocstrings-python = ">=1.16.2,<2"
pymdown-extensions = ">=10.14.3,<11"
mkdocs-table-reader-plugin = ">=3.1.0,<4"
mkdocs-gen-files = ">=0.4.0,<0.5"
mkdocs-macros-plugin = ">=1.3.7,<2"
mkdocs-jupyter = ">=0.25.1,<0.26"
mkdocs-glightbox = ">=0.4.0,<0.5"
mkdocs-git-revision-date-localized-plugin = ">=1.2.9,<2"

[feature.docs.pypi-dependencies]
material-plausible-plugin = ">=0.2.0,<0.3"
mkdocs-print-site-plugin = ">=2.6.0,<3"
mkdocs-awesome-nav = ">=3.0.0,<4"

[feature.docs.tasks]
docs = { cmd = ["rm", "-rf", "./public/", "&&", "mkdocs", "build", "-d", "public/"] }
serve = { cmd = ["mkdocs", "serve"] }
